### ISSUE TITLE
Implementation Bug -- first entry of published log has SCID as the entryHash item

### ISSUE THREAD

**Issue by swcurran** [decentralized-identity/trustdidweb-ts#12]
I note that in the published log, the `entryHash` item in the first line is the value of the DID's SCID.  It shouldn't be. The SCID should be used as input to the generation of the hash that is then put into the `entryHash` item.  It appears that the `entryHash` calculation is being done, as the `challenge` in the DI proof is a proper hash. However, it looks like the SCID is not being replaced as the first item in the JSON Line array for publication.

**Comment by brianorwhatever** [comment]
This bug has been fixed
