### ISSUE TITLE
secp256k1 key support

### ISSUE THREAD

**Issue by lemoustachiste** [decentralized-identity/trustdidweb-ts#15]
Hi,

I'm doing some research on did:tdw and our system is mostly working with secp256k1 keys. 

While I was able to quickly create a DID and DID doc with a secp256k1 key pair, resolving and subsequent verification of the log fails, as it seems to be expecting Ed25519 keys only.

Is there a plan to add official support for secp256k1 keys?

Could you also confirm my understanding that the log is signed by the key pair held in the DID doc? It seems obvious but I'm not always correct.

Thanks

**Comment by brianorwhatever** [comment]
Hello Julien,

I think this issue would be better for the specification repo [here](https://github.com/bcgov/trustdidweb). As of right now there aren't plans to add new crypto suites but we have designed the method to allow others in the future. The more vocal people are about the cryptosuite they want the more likely they will be added so please create an issue in the spec repo.

As for the key that is allowed to update you will find an explanation [here](https://bcgov.github.io/trustdidweb/#authorized-keys). We actually moved them out of the did doc they are now in the "updateKeys" parameter in the log which is external to the did doc. This doesn't forbid anyone from also including it in the did doc.

Hope that helps!

**Comment by lemoustachiste** [comment]
Hi Brian,

I was able to generate, resolve and verify a local secp256k1 DID:TDW documents pair. It required a minimal adjustment to the code.

I'm continuing the exploration of the solution, and I haven't opened anything on the spec repo for now. 

Would you want to see a WIP PR to get a feel of the work?

**Comment by brianorwhatever** [comment]
Closing this as secp256k1 support is currently available in a DID Doc and support for using it as an `updateKey` would need to be added to the specification before being implemented here.
