### ISSUE TITLE
DID Resolver

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/trustdidweb-ts#2]
We can easily add an http resolver that would proxy to external DIDs. It gets a bit more challenging when we want to be resolving documents from the local filesystem. The biggest thing to think about is how do the files get to the filesystem.

I propose an upload endpoint that receives a log file and stores it to disk (only if the version is higher than currently saved and the log verifies).

**Comment by brianorwhatever** [comment]
`method.resolveDID` now resolves a DID by grabbing the log and then verifying it using `method.resolveDIDFromLog` which expects a log and will resolve a DID from it.

The resolver is now available in the universal resolver. Will add `did:webvh` to the uni resolver once we have a stable version.

**Comment by lemoustachiste** [comment]
> did:webvh

I have followed the sort of legal battle for afar, but is this the new name for `did:tdw`?

**Comment by brianorwhatever** [comment]
Yeah, that's right
