### ISSUE TITLE
nextKeyHashes Disappeared when the document is version 1

### ISSUE THREAD

**Issue by hello0827** [decentralized-identity/trustdidweb-ts#20]
Hi All, I am new to create issue in a open source repo and please feel free to correct me if I am wrong or not appropriate 🙏 

I found that when the prerotation is enabled for createDID when the log is version 1(v1), the v1 log cannot resolve the nextKeyHash in meta by calling resolveDID,  such that when I am call updateDID to rotate the key to v2, it caused error.

The output of resolveDID for v1Log:
<img width="874" alt="image" src="https://github.com/user-attachments/assets/56b1a383-d21c-41a3-b23e-186dec0f8c4e">

when I am updating the DID with pre-rotated key
<img width="869" alt="image" src="https://github.com/user-attachments/assets/588a3722-5c2d-4617-8182-6112b88f1596">

After tracking the code, I found the issue should caused by src/method.ts line 138-139
https://github.com/decentralized-identity/trustdidweb-ts/blob/67b6b2c12d49167eabba56ef9632820213eda8a2/src/method.ts#L138-L139

After I fix the code like this, the pre rotation works properly 

```
meta.nextKeyHashes = parameters.nextKeyHashes ?? [];

newKeysAreValid(meta.updateKeys, [], meta.nextKeyHashes, false, meta.prerotation === true);

```

**Comment by brianorwhatever** [comment]
Thank you! This should be fixed in #23
