### ISSUE TITLE
Handle multiple proofs

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/trustdidweb-ts#5]
Things will without a doubt blow up when multiple proofs are found on a log entry. This will need to be handled later when multiple proofs are a thing.

**Comment by andrewwhitehead** [comment]
We should probably accept it if any of the proofs on the log entry are sufficient, or in the 'verifiable conditions' case if the conditions are met.

**Comment by brianorwhatever** [comment]
Library handles multiple proofs now (as a set)
